[workspace]
resolver = "2"
members = [
		"crates/tuono",
		"crates/tuono_lib",
		"crates/tuono_lib_macros",
]
exclude = [
		"apps/documentation",
		"examples/with-mdx",
		"examples/tuono-app",
		"examples/tuono-api",
		"examples/tuono-tutorial",
		"benches/tuono"
]
