[workspace]
resolver = "2"
members = [
		"crates/tuono",
		"crates/tuono_lib",
		"crates/tuono_lib_macros",
]
exclude = [
		"apps/documentation",
		"examples/mdx",
		"examples/tuono",
		"examples/tutorial",
		"benches/tuono"
]
