// This file is auto-generated by Tuono

import { createRoute, dynamic } from 'tuono'

import RootImport from './routes/__root'

const PostsrootImport = dynamic(() => import('./routes/posts/__root'))
const AboutImport = dynamic(() => import('./routes/about'))
const IndexImport = dynamic(() => import('./routes/index'))
const PostsMyPostImport = dynamic(() => import('./routes/posts/my-post'))

const rootRoute = createRoute({ isRoot: true, component: RootImport })

const Postsroot = createRoute({
  component: PostsrootImport,
  getParentRoute: () => rootRoute,
})

const About = createRoute({ component: AboutImport })
const Index = createRoute({ component: IndexImport })
const PostsMyPost = createRoute({ component: PostsMyPostImport })

// Create/Update Routes

const AboutRoute = About.update({
  path: '/about',
  getParentRoute: () => rootRoute,
})

const IndexRoute = Index.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const PostsMyPostRoute = PostsMyPost.update({
  path: '/posts/my-post',
  getParentRoute: () => Postsroot,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  PostsMyPostRoute,
])
