// This file is auto-generated by Tuono

import { createRoute, dynamic } from 'tuono'

import RootImport from './routes/__root'

const IndexImport = dynamic(() => import('./routes/index'))
const PostscatchallImport = dynamic(
  () => import('./routes/posts/[...catch_all]'),
)

const rootRoute = createRoute({ isRoot: true, component: RootImport })

const Index = createRoute({ component: IndexImport })
const Postscatchall = createRoute({ component: PostscatchallImport })

// Create/Update Routes

const IndexRoute = Index.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const PostscatchallRoute = Postscatchall.update({
  path: '/posts/[...catch_all]',
  getParentRoute: () => rootRoute,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexRoute, PostscatchallRoute])
