// This file is auto-generated by Tuono

import { createRoute } from 'tuono'

import RootImport from './routes/__root'

import AboutImport from './routes/about'
import IndexImport from './routes/index'
import PostsIndexImport from './routes/posts/index'
import PostsPostSlugImport from './routes/posts/post-slug'

const rootRoute = createRoute({ isRoot: true, component: RootImport })

const About = createRoute({ component: AboutImport })
const Index = createRoute({ component: IndexImport })
const PostsIndex = createRoute({ component: PostsIndexImport })
const PostsPostSlug = createRoute({ component: PostsPostSlugImport })

// Create/Update Routes

const AboutRoute = About.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = Index.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndex.update({
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostSlugRoute = PostsPostSlug.update({
  path: '/posts/post-slug',
  getParentRoute: () => rootRoute,
} as any)

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  PostsPostSlugRoute,
  PostsIndexRoute,
])
