name: Documentation Website CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'apps/documentation/**'
  pull_request:
    paths:
      - '.github/**'
      - 'apps/documentation/**'

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: Check build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install tuono
        run: cargo install tuono@0.12.3

      - name: Build project
        working-directory: ./apps/documentation
        run: tuono build --static

  fmt-lint-and-types:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: Check format and lint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Check formatting
        run: pnpm docs:format:check

      - name: Lint
        run: pnpm docs:lint

      - name: Types
        run: pnpm docs:types
