name: Documentation Website CI

on:
  push:
    branches:
      - 'main'
    paths:
      # ⬇ Keep paths in sync with `typescript.yml`
      - '.github/**'
      - '*'
      - '!Cargo.toml'
      # ⬆ Keep paths in sync with `typescript.yml`
      - 'apps/documentation/**'
  pull_request:
    paths:
      # ⬇ Keep paths in sync with `typescript.yml`
      - '.github/**'
      - '*'
      - '!Cargo.toml'
      # ⬆ Keep paths in sync with `typescript.yml`
      - 'apps/documentation/**'

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install tuono
        run: cargo install tuono@0.15.0

      - name: Build project
        working-directory: ./apps/documentation
        run: tuono build --static

  code_check:
    name: Check format, lint and types
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Check formatting
        run: pnpm docs:format:check

      - name: Lint
        run: pnpm docs:lint

      - name: Types
        run: pnpm docs:types
