name: Documentation Website CI

on:
  push:
    paths:
      - '.github/**'
      - 'apps/documentation/**'
  pull_request:
    paths:
      - '.github/**'
      - 'apps/documentation/**'

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install tuono
        run: cargo install tuono@0.12.3

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        working-directory: ./apps/documentation
        run: tuono build --static

  fmt-lint-and-types:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm docs:format:check

      - name: Lint
        run: pnpm docs:lint

      - name: Types
        run: pnpm docs:types
